### ISSUE TITLE
Modify tests

### ISSUE THREAD

**Issue by NikMatyukhin** [Illinoize/PythonProjectDjango#3]
Now you prepare all data (users, wallets AND TRANSACTIONS) in fixtures. Prepare only users.

Wallets tests need test client to send requests. And then you can check wallet balance. Now you set balance 100 RUB and check wallet.balance == 100 RUB. This test dont check anything.
Transactions tests need test client to send requests. And then you can check transactions in database.

**Comment by Illinoize** [comment]
Tests were updated
